[package]
name = "relay"
description = "A simple activitypub relay"
version = "0.2.5"
authors = ["asonix <asonix@asonix.dog>"]
license-file = "LICENSE"
readme = "README.md"
repository = "https://git.asonix.dog/asonix/ap-relay"
keywords = ["activitypub", "relay"]
edition = "2018"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
actix-rt = "1.1.1"
actix-web = { version = "3.3.2", default-features = false, features = ["rustls", "compress"] }
actix-webfinger = "0.3.0"
activitystreams = "0.7.0-alpha.9"
activitystreams-ext = "0.1.0-alpha.2"
ammonia = "3.1.0"
async-mutex = "1.0.1"
async-rwlock = "1.3.0"
background-jobs = "0.8.0"
base64 = "0.13"
chrono = "0.4.19"
config = "0.10.1"
dotenv = "0.15.0"
env_logger = "0.8.2"
futures = "0.3.4"
http-signature-normalization-actix = { version = "0.4.0", default-features = false, features = ["sha-2"] }
log = "0.4"
lru = "0.6.0"
mime = "0.3.16"
num_cpus = "1.12"
pretty_env_logger = "0.4.0"
rand = "0.7"
rsa = "0.3"
rsa-magic-public-key = "0.2.0"
rsa-pem = "0.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.9"
sled = "0.34.6"
structopt = "0.3.12"
thiserror = "1.0"
uuid = { version = "0.8", features = ["v4", "serde"] }

[build-dependencies]
anyhow = "1.0"
dotenv = "0.15.0"
ructe = { version = "0.13.0", features = ["sass", "mime03"] }

[profile.dev.package.rsa]
opt-level = 3
